version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php

  php:
    image: php:latest
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mongo
    command: ["php", "-S", "0.0.0.0:80", "-t", "/var/www/html"]

  mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db

  composer:
    image: composer/composer:latest
    volumes:
      - ./src:/app
    command: ["sleep", "infinity"]

  