version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:latest
    ports:
      - "3000:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mongo
    command: tail -f /dev/null

  mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db

