services:
  nginx:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - my-net
  composer:
    image: composer:latest
    volumes:
      - ./src:/app
    command: install
    networks:
      - my-net
  php:
    image: php:fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - my-net
networks:
  my-net:

