FROM php:fpm

RUN apt-get update \
    && apt-get install -y libssl-dev \
    && pecl install mongodb \
    && docker-php-ext-enable mongodb \
    && pecl install symfony \
    && docker-php-ext-enable symfony \
    && echo "extension=mongodb.so" > /usr/local/etc/php/conf.d/mongodb.ini\
    && echo "extension=symfony.so" > /usr/local/etc/php/conf.d/symfony.ini

